#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : trustme
Version  : 0.6.0
Release  : 4
URL      : https://files.pythonhosted.org/packages/76/de/8dc6d402ac6037ee419a4f8bf29b4374068f0517a599234adfcfcc961bc8/trustme-0.6.0.tar.gz
Source0  : https://files.pythonhosted.org/packages/76/de/8dc6d402ac6037ee419a4f8bf29b4374068f0517a599234adfcfcc961bc8/trustme-0.6.0.tar.gz
Summary  : #1 quality TLS certs while you wait, for the discerning tester
Group    : Development/Tools
License  : Apache-2.0 MIT
Requires: trustme-license = %{version}-%{release}
Requires: trustme-python = %{version}-%{release}
Requires: trustme-python3 = %{version}-%{release}
Requires: cryptography
Requires: idna
BuildRequires : buildreq-distutils3
BuildRequires : cryptography
BuildRequires : idna

%description
==============================================

%package license
Summary: license components for the trustme package.
Group: Default

%description license
license components for the trustme package.


%package python
Summary: python components for the trustme package.
Group: Default
Requires: trustme-python3 = %{version}-%{release}

%description python
python components for the trustme package.


%package python3
Summary: python3 components for the trustme package.
Group: Default
Requires: python3-core
Provides: pypi(trustme)
Requires: pypi(cryptography)
Requires: pypi(idna)

%description python3
python3 components for the trustme package.


%prep
%setup -q -n trustme-0.6.0
cd %{_builddir}/trustme-0.6.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1588358643
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/trustme
cp %{_builddir}/trustme-0.6.0/LICENSE %{buildroot}/usr/share/package-licenses/trustme/304509f864a3be91c9528f012a52c5266647cca7
cp %{_builddir}/trustme-0.6.0/LICENSE.APACHE2 %{buildroot}/usr/share/package-licenses/trustme/2b8b815229aa8a61e483fb4ba0588b8b6c491890
cp %{_builddir}/trustme-0.6.0/LICENSE.MIT %{buildroot}/usr/share/package-licenses/trustme/f8c5fdc67d412f3435473ee8ce595f06d921ca44
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/trustme/2b8b815229aa8a61e483fb4ba0588b8b6c491890
/usr/share/package-licenses/trustme/304509f864a3be91c9528f012a52c5266647cca7
/usr/share/package-licenses/trustme/f8c5fdc67d412f3435473ee8ce595f06d921ca44

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
